.localvar 0 arguments

:[0]
pushi.e 0
pop.v.i self.legl
pushi.e 0
pop.v.i self.legr
pushi.e 0
pop.v.i self.arml
pushi.e 0
pop.v.i self.armr
pushi.e 0
pop.v.i self.leglh
pushi.e 0
pop.v.i self.legrh
pushi.e 0
pop.v.i self.xoffr
pushi.e 0
pop.v.i self.yoffl
pushi.e 0
pop.v.i self.xoffr
pushi.e 0
pop.v.i self.yoffl
pushi.e 0
pop.v.i self.siner
pushi.e 0
pop.v.i self.lsin
pushi.e 0
pop.v.i self.rsin
pushi.e 0
pop.v.i self.faceno
pushi.e 0
pop.v.i self.side
pushi.e 0
pop.v.i self.prevside
pushi.e 2
pop.v.i self.hurt
pushi.e 0
pop.v.i self.hurtface
pushi.e 1
pop.v.i self.myalpha
push.i 16777215
pop.v.i self.myblend
pushi.e 1
pop.v.i self.sineron
pushi.e 0
pop.v.i self.pause
pushi.e 0
pop.v.i self.legmode
pushi.e 25
pop.v.i self.dancewait
push.v self.dancewait
pushi.e 5
mul.i.v
pushi.e -1
pushi.e 5
pop.v.v [array]self.alarm
pushi.e 0
pop.v.i self.dsf
pushi.e 0
pop.v.i self.ds
pushi.e 0
pop.v.i self.fadewhite
pushi.e 0
pop.v.i self.whiteval
pushi.e 0
pop.v.i self.bodyopen
pushi.e 0
pop.v.i self.bodyimg
pushi.e 0
pop.v.i self.heartdead
pushi.e 1
pop.v.i self.dance
pushi.e 5
pushi.e -1
pushi.e 6
pop.v.i [array]self.alarm
pushi.e 0
pop.v.i self.noarm
pushi.e 0
pop.v.i self.noleg
pushi.e 0
pop.v.i self.endface
pushi.e 0
pop.v.i self.face_set
pushi.e 0
pop.v.i self.do_room_goto

:[end]