.localvar 0 arguments

:[0]
pushi.e 320
pop.v.i self.x
pushi.e 0
pop.v.i self.a_type
pushi.e 0
pop.v.i self.drawborder
pushi.e 4
pop.v.i global.faceemotion
pushi.e 0
pushi.e -5
pushi.e 20
pop.v.i [array]global.flag
pushi.e 0
pop.v.i self.sweat
pushi.e 0
pop.v.i self.pause
pushi.e 0
pop.v.i self.bounce
pushi.e 0
pop.v.i self.siner
pushi.e 0
pop.v.i self.yoff
pushi.e 0
pop.v.i self.xoff
pushi.e 0
pop.v.i self.legx
pushi.e 0
pop.v.i self.legy
pushi.e 0
pop.v.i self.deadtest
pushi.e 0
pop.v.i self.repeater
pushi.e 0
pop.v.i self.movearm
pushi.e 0
pop.v.i self.arm_i
pushi.e 0
pop.v.i self.heady
pushi.e 0
pop.v.i self.headx
pushi.e 1
pop.v.i self.aspeed
pushi.e 0
pop.v.i self.facetype
pushi.e 0
pop.v.i self.f_i
pushi.e 0
pop.v.i self.hell
pushi.e 0
pop.v.i self.fac
pushi.e 0
pop.v.i self.lac
pushi.e 0
pop.v.i self.mk_c
pushi.e 15
pop.v.i self.intensity
pushi.e 0
pop.v.i self.smasher
pushi.e 4
pop.v.i self.smashtime
pushi.e 0
pop.v.i self.smashcon
pushi.e 2
pop.v.i self.smashlv
pushi.e 0
pop.v.i self.smashamt
pushi.e 8
pop.v.i self.smashmax
pushi.e -1
pop.v.i self.prevsmash
pushi.e 0
pop.v.i self.test_timer
pushi.e 0
pop.v.i self.test_timer_on
pushi.e 0
pop.v.i self.dodge
pushi.e 0
pop.v.i self.death_c
pushi.e 0
pop.v.i self.death_t
pushi.e 0
pop.v.i self.asleep
pushi.e 0
pop.v.i self.asleep_timer
pushi.e 0
pop.v.i self.sleep_c
pushi.e 0
pop.v.i self.sleep_t
pushi.e 0
pop.v.i self.km_t
pushglb.v global.hp
pop.v.v self.prevhp
pushi.e 0
pop.v.i self.damageturn
pushi.e 0
pop.v.i self.inv_check
pushi.e 0
pop.v.i self.inv_timer
pushi.e -1
pop.v.i global.damagetimer
pushi.e 0
pop.v.i self.do_room_goto

:[end]