.localvar 0 arguments

:[0]
pushglb.v global.asp
pop.v.v global.sp
pushi.e 0
pop.v.i self.movement
pushi.e 0
pop.v.i self.jumpstage
pushi.e 0
pop.v.i self.hgo
pushi.e 0
pop.v.i self.vgo
pushi.e 0
pop.v.i self.shot
pushi.e 0
pop.v.i global.bmenuno
pushi.e 0
pushi.e -5
pushi.e 0
pop.v.i [array]global.bmenucoord
pushi.e 0
pushi.e -5
pushi.e 1
pop.v.i [array]global.bmenucoord
pushi.e 0
pushi.e -5
pushi.e 2
pop.v.i [array]global.bmenucoord
pushi.e 0
pushi.e -5
pushi.e 3
pop.v.i [array]global.bmenucoord
pushi.e 0
pushi.e -5
pushi.e 4
pop.v.i [array]global.bmenucoord
pushi.e 0
pushi.e -5
pushi.e 6
pop.v.i [array]global.bmenucoord
pushi.e 0
pushi.e -5
pushi.e 7
pop.v.i [array]global.bmenucoord
pushi.e 0
pushi.e -5
pushi.e 8
pop.v.i [array]global.bmenucoord
pushi.e 0
pushi.e -5
pushi.e 9
pop.v.i [array]global.bmenucoord
pushi.e 0
pushi.e -5
pushi.e 10
pop.v.i [array]global.bmenucoord
pushi.e 0
pushi.e -5
pushi.e 0
pop.v.i [array]global.hurtanim
pushi.e 0
pushi.e -5
pushi.e 1
pop.v.i [array]global.hurtanim
pushi.e 0
pushi.e -5
pushi.e 2
pop.v.i [array]global.hurtanim
pushi.e 0
pushi.e -5
pushi.e 3
pop.v.i [array]global.hurtanim
pushi.e 0
pop.v.i global.myfight
pushi.e 0
pop.v.i global.mnfight
pushi.e 0
pushi.e -5
pushi.e 3
pop.v.i [array]global.xpreward
pushi.e 0
pushi.e -5
pushi.e 3
pop.v.i [array]global.goldreward
pushi.e 0
pop.v.i self.confuse
pushi.e 0
pop.v.i self.charge
pushi.e 0
pop.v.i self.ignore_border
pushi.e 0
pop.v.i self.slam_pain

:[end]