.localvar 0 arguments

:[0]
pushi.e 68
pushi.e -1
pushi.e 7
pop.v.i [array]self.partx
pushi.e 0
pushi.e -1
pushi.e 7
pop.v.i [array]self.party
pushi.e 0
pushi.e -1
pushi.e 6
pop.v.i [array]self.partx
pushi.e 28
pushi.e -1
pushi.e 6
pop.v.i [array]self.party
pushi.e 16
pushi.e -1
pushi.e 5
pop.v.i [array]self.partx
pushi.e 70
pushi.e -1
pushi.e 5
pop.v.i [array]self.party
pushi.e 168
pushi.e -1
pushi.e 4
pop.v.i [array]self.partx
pushi.e 70
pushi.e -1
pushi.e 4
pop.v.i [array]self.party
pushi.e 50
pushi.e -1
pushi.e 3
pop.v.i [array]self.partx
pushi.e 130
pushi.e -1
pushi.e 3
pop.v.i [array]self.party
pushi.e 54
pushi.e -1
pushi.e 2
pop.v.i [array]self.partx
pushi.e 156
pushi.e -1
pushi.e 2
pop.v.i [array]self.party
pushi.e 32
pushi.e -1
pushi.e 1
pop.v.i [array]self.partx
pushi.e 210
pushi.e -1
pushi.e 1
pop.v.i [array]self.party
pushi.e -48
pushi.e -1
pushi.e 0
pop.v.i [array]self.partx
pushi.e 62
pushi.e -1
pushi.e 0
pop.v.i [array]self.party
pushi.e 636
pushi.e -1
pushi.e 7
pop.v.i [array]self.part
pushi.e 637
pushi.e -1
pushi.e 6
pop.v.i [array]self.part
pushi.e 634
pushi.e -1
pushi.e 5
pop.v.i [array]self.part
pushi.e 635
pushi.e -1
pushi.e 4
pop.v.i [array]self.part
pushi.e 638
pushi.e -1
pushi.e 3
pop.v.i [array]self.part
pushi.e 639
pushi.e -1
pushi.e 2
pop.v.i [array]self.part
pushi.e 640
pushi.e -1
pushi.e 1
pop.v.i [array]self.part
pushi.e 632
pushi.e -1
pushi.e 0
pop.v.i [array]self.part
pushi.e 0
pop.v.i self.fakeanim
pushi.e 0
pop.v.i self.siner
pushi.e 1
pop.v.i self.moving
pushi.e 0
pop.v.i self.pause

:[end]